### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by mohammed-elattar** [zizohassan/laraflat#27]
I am experiencing this issue during installation  , i tried many times but it didn't work at all 
![capture](https://user-images.githubusercontent.com/16066732/31812495-74d18eea-b583-11e7-92e9-f4bcfefa7e98.PNG)
Please check the pic and let me know if the issue from my side , how can i sort it out 
Thanks in advance

**Comment by mohammed-elattar** [comment]
I downloaded the repo as zip and i run composer install and it worked fine but till now i dont know how to install it using composer however i can install anything else with composer for example a laravel project ,
i am watching you series that explain the laraflat project but the one which i download is different in its theme , please let me know if i misunderstand anything 
thanks in advance , i really appreciate your effort

**Comment by zizohassan** [comment]
about the theme 
we support two theme on laraflat project you can switch btween them in env file (THEME = themeone , default)
about composer problem its about windows only the composer run fine on linux and mac system 
because length was bigger than what windows allows ,
you can download zip file and run composer install it will work fine

**Comment by mohammed-elattar** [comment]
Many thanks for your decent support :+1:

**Comment by zizohassan** [comment]
you are welcome
