### ISSUE TITLE
Permission denied on ubuntu file put contain 

### ISSUE THREAD

**Issue by badrshs** [zizohassan/laraflat#88]
if you are working on ubuntu server you most give permission to resource  , config , app  and database folders  . 

this is required when you use Laraflat Commands new model  like post .

you may missed to add those thing to your documentation .

thank you for your amazing job 

another thing , your project seems like slower than before , sometime it need really long time to go to another page , I got this problem today on real server ,I think the problem because you are tracking the visitors . is there is anyway to stop that  ?

**Comment by zizohassan** [comment]
in real server you just keep public folder and you are secure ,
you must secure config folder and .env file this is the most important part

if you think its slow because the package of tracking visitors you can remove it 
remove the backage "consoletvs/links": "^1.0",
from composer
remove this from website theme 
{!! Links::track() !!}

**Comment by badrshs** [comment]
yes I Know that , it's secure but I mean because some of your (file_put_contents)functions the people must give permission to the folders that I told you above ,
which is not written in your documentation .

I got that problem when I test your package on real server 

thank you anyway

**Comment by zizohassan** [comment]
yes ok i will update the docs 
thanks
